//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace whiteMath.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("whiteMath.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B	N	P	NROOT
        ///2	4	17	13
        ///2	8	41	27
        ///2	16	97	8
        ///2	32	193	185
        ///2	64	257	81
        ///2	128	641	243
        ///2	256	3329	3061
        ///2	512	7681	7146
        ///2	1024	12289	10302
        ///2	2048	12289	1945
        ///2	4096	40961	18088
        ///2	8192	40961	243
        ///2	16384	65537	81
        ///2	32768	163841	243
        ///2	65536	786433	108788
        ///2	131072	786433	213567
        ///2	262144	5767169	1893080
        ///2	524288	5767169	177147
        ///2	1048576	7340033	2187
        ///2	2097152	23068673	177147
        ///2	4194304	104857601	39193363
        ///2	8388608	167772161	131341181
        ///2	16777216	167772161	59049
        ///2	33554432	167772161	243
        ///2	67108864	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTTPrimeModuli {
            get {
                return ResourceManager.GetString("NTTPrimeModuli", resourceCulture);
            }
        }
    }
}
